// This file is generated by Slice Machine. Update with care!

import CtaSection from './CtaSection';
import Faqs from './Faqs';
import Partners from './Partners';
import ShortStory from './ShortStory';

export {
	CtaSection,
	Faqs,
	Partners,
	ShortStory,
};

export const components = {
	cta_section: CtaSection,
	faqs: Faqs,
	partners: Partners,
	short_story: ShortStory,
};
